### ISSUE TITLE
switchboard-plug-datetime crashes when opened

### ISSUE THREAD

**Issue by austinmarner** [decathorpe/elementary-staging-rpms#2]
Date and time settings crash and close the entire settings if opened I tried to open through system settings as well as using the wingpanel but the settings crash if I open date and time settings

**Comment by austinmarner** [comment]
I ran io.elementary.switchboard through the terminal and it returned the below log when I open the date and time settings

(io.elementary.switchboard:2723): GLib-GIO-ERROR **: 17:18:48.073: Settings schema 'io.elementary.desktop.wingpanel.datetime' does not contain a key named 'clock-format'
Trace/breakpoint trap (core dumped)

**Comment by decathorpe** [comment]
Are you using the `switchboard-plug-datetime` package from the `elementary-staging` or the `elementary-nightly` COPR repository?

**Comment by austinmarner** [comment]
from nightly repo

**Comment by decathorpe** [comment]
The crash should be fixed now, both for:

- staging: https://copr.fedorainfracloud.org/coprs/decathorpe/elementary-staging/build/884780/
- nightly: https://copr.fedorainfracloud.org/coprs/decathorpe/elementary-nightly/build/884783/

**Comment by austinmarner** [comment]
Yup...

It's working now
