### ISSUE TITLE
Bluetooth icon not visible in wingpanel

### ISSUE THREAD

**Issue by austinmarner** [decathorpe/elementary-staging-rpms#4]
I have upgraded to Fedora 30 and now the Bluetooth icon in wingpanel is not visible

![Screenshot from 2019-04-18 22 57 31](https://user-images.githubusercontent.com/45146774/56379462-693a7580-622d-11e9-9436-abd5fb2b03c6.png)

**Comment by decathorpe** [comment]
You mean the blank space between the wired network symbol and the battery status?

**Comment by austinmarner** [comment]
Yeah... It shows options for Bluetooth when I click but the icon is not visible

**Comment by austinmarner** [comment]
Sorry for my stupidity, that's my brother

**Comment by decathorpe** [comment]
Can you try the following:

1. open two terminal windows
2. run `journalctl -xb --user --follow` in one of them
3. run `killall wingpanel` in the other one

This should kill and then restart wingpanel, and in the logs in the first window, there should be a message about which icon wingpanel is trying to load but doesn't find.

**Comment by austinmarner** [comment]
log:

-- Logs begin at Wed 2019-04-17 00:26:13 IST. --
Apr 19 08:13:38 Fedora-X510UNR systemd[1282]: run-user-978.mount: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- The unit UNIT has successfully entered the 'dead' state.
Apr 19 08:13:38 Fedora-X510UNR gala[1514]: g_variant_get_byte: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_BYTE)' failed
Apr 19 08:13:39 Fedora-X510UNR gala[1514]: g_variant_get_byte: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_BYTE)' failed
Apr 19 08:13:39 Fedora-X510UNR gala[1514]: g_variant_get_byte: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_BYTE)' failed
Apr 19 08:13:39 Fedora-X510UNR gala[1514]: g_variant_get_byte: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_BYTE)' failed
Apr 19 08:13:39 Fedora-X510UNR gala[1514]: g_variant_get_byte: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_BYTE)' failed
Apr 19 08:13:39 Fedora-X510UNR gala[1514]: g_variant_get_byte: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_BYTE)' failed
Apr 19 08:13:39 Fedora-X510UNR gala[1514]: g_variant_get_byte: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_BYTE)' failed
Apr 19 08:13:39 Fedora-X510UNR gala[1514]: g_variant_get_byte: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_BYTE)' failed
Apr 19 08:14:10 Fedora-X510UNR io.elementary.t[2259]: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook
Apr 19 08:14:33 Fedora-X510UNR io.elementary.c[1570]: ProcessWrapper.vala:99: Process 'wingpanel' watch exit
Apr 19 08:14:33 Fedora-X510UNR io.elementary.c[1570]: ProcessWrapper.vala:111: Process wingpanel is being terminated
Apr 19 08:14:33 Fedora-X510UNR io.elementary.c[1570]: ProcessWrapper.vala:123: ET = 64.109804 secs        Min allowed time = 3.500000
Apr 19 08:14:33 Fedora-X510UNR io.elementary.c[1570]: ProcessWrapper.vala:46: Crash count of 'wingpanel' has been reset
Apr 19 08:14:33 Fedora-X510UNR gala[1514]: Failed to fetch xid: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.ayatana.bamf.window” on object at path /org/ayatana/bamf/window/29360131
Apr 19 08:14:33 Fedora-X510UNR gala[1514]: Failed to fetch type: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.ayatana.bamf.window” on object at path /org/ayatana/bamf/window/29360131
Apr 19 08:14:33 Fedora-X510UNR gala[1514]: Failed to fetch monitor: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.ayatana.bamf.window” on object at path /org/ayatana/bamf/window/29360131
Apr 19 08:14:33 Fedora-X510UNR gala[1514]: Failed to fetch maximized state: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.ayatana.bamf.window” on object at path /org/ayatana/bamf/window/29360131
Apr 19 08:14:33 Fedora-X510UNR gala[1514]: Failed to fetch xid: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.ayatana.bamf.window” on object at path /org/ayatana/bamf/window/29360131
Apr 19 08:14:33 Fedora-X510UNR gala[1514]: Unable to fetch children: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.ayatana.bamf.view” on object at path /org/ayatana/bamf/application/159554366
Apr 19 08:14:33 Fedora-X510UNR gala[1514]: Failed to fetch path: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.ayatana.bamf.application” on object at path /org/ayatana/bamf/application/159554366
Apr 19 08:14:34 Fedora-X510UNR wingpanel[2366]: Theme parsing error: <broken file>:1:0: Failed to import: The resource at “/io/elementary/wingpanel/nightlight/indicator.css” does not exist
Apr 19 08:14:34 Fedora-X510UNR wingpanel[2366]: Theme parsing error: <broken file>:1:0: Failed to import: The resource at “/io/elementary/wingpanel/sound/indicator.css” does not exist
Apr 19 08:14:34 Fedora-X510UNR wingpanel[2366]: Theme parsing error: <broken file>:1:0: Failed to import: The resource at “/io/elementary/wingpanel/bluetooth/indicator.css” does not exist
Apr 19 08:14:34 Fedora-X510UNR gala[1514]: invalid cast from 'CoglTexture2D' to '(null)'

**Comment by austinmarner** [comment]
yup after the update it's now showing up in wingpanel

**Comment by decathorpe** [comment]
Which update? 😅 But as long as it's working now, it's good ...

**Comment by austinmarner** [comment]
I received an update yesterday for wingpanel-indicator-bluetooth, after that it's fine and showing up in the panel

**Comment by decathorpe** [comment]
Ok, good to know!
